---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: "registryyzk4661.azurecr.io/tripinsights/jtuserprofile:1.0"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_DBNAME
          - name: PORT
            value: '80'
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: userprofile