---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: poi
        image: "registryyzk4661.azurecr.io/tripinsights/poi:1.0"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_DBNAME
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Local'
          - name: WEB_PORT
            value: '80'
          - name: WEB_SERVER_BASE_URI
            value: 'http://0.0.0.0'
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: poi