---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: user-java
        image: "registryyzk4661.azurecr.io/tripinsights/user-java:1.0"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_DBNAME
          - name: PORT
            value: '80'
---
apiVersion: v1
kind: Service
metadata:
  name: user-java
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: user-java