---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: trips
        image: "registryyzk4661.azurecr.io/tripinsights/trips:1.0"
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_PASSWORD
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: SQL_DBNAME
          - name: DEBUG_LOGGING
            value: 'false'
          - name: PORT
            value: '80'
          - name: OPENAPI_DOCS_URI
            value: 'http://52.226.194.225'
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: trips