apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQXRDZ0F3SUJBZ0lRTDVkS3hNYVRNZ2Y4cDhiTlZuMERiVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWdGdzB5TVRFeE1qVXdOREl6TWpSYUdBOHlNRFV4TVRFeU5UQTBNek15TkZvdwpEVEVMTUFrR0ExVUVBeE1DWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURICk82Uy9qUGM3S0xhZG03UmNUSCs2ME9FVzNrVDBSRDh5ZWlCeG9ieTNmUHpNQmhnTFN6M2VjWWk4azFLN29FS2EKR2hDYmpIYzZ5dUNOb1k3WXR0blB2c091U2NReHNiTTA0d0pJcm9GUmlUbm1zNzJ3Z3lEVVlYcFNNb29WQVFFMApIWmE2YWdiNjk2bnFlVUU5TVdadGM1YU05MUtoTGYyWXBxSElRdDFhUFUxTExwRVVOTUl2ZS92d0FMcHBTTmNpCnIveVE2eFp2VHNvSG85VWxyVUlqeUhCSUVKYUUxNGk4UGhOeklkZTZkcmY5Y0lDbjNnQzBXamVPY2lzOEVBS1oKczRRZWp4Y2srWW1OQnM4cndtUnkyOVBMUXJTQytDRkRVeHlGZ1Y3eVFXUFNSRzVBbnJ1ZW9XdjdlQnFmYzZXMApzZXloL0J6SGxZcVU3UCtBRWxsZ3dnRHV3M2dLVThnVE9vWmlhbFdOb0VOM2dTaWkxUjEzWm9MVFNkUTVSV25hCnpiTFpFc2tNaTQwWmlrUFV0bzBvZkZOSDdHRzUxUnJVWWV5SWJQWEQraXpTY3Q3U1RweGlUK0hUMnFJcVQ1cFkKN3kyblJ1dURZT0pybnNTSkNUSmsvQzFQRUhUVkxQbW4zU1AvOEhLblJTYzVqUFVMdXA5S1FZVlhhY1B2dVhYZQpRb2trMEFiTm03U1hYRWRkSDZCVVk3U25ueHRtcHFjV2RRRlVFbE13UFJEQWlZdTEwVFJVSGx1MVFNcU92aW5DCkx4TVpNRURIUi9wQVBCaW5KaWtqc2w1SVI4dmxXZE1sL0YvNGpHZWQvR24wS2RQN0NDNjVMMjQvY2wyNUR6aVYKaGZ6R0RlR0N5T05pcTBoNDcvUmVpSks0MW9QUThjK3FqVHI2Q0xURFV3SURBUUFCbzBJd1FEQU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVV3eGMxMVphSXhYU3VNdy9LCkZwY2ZERzBGbGtBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFMek1CaDVUTVk0UENUT1I0TG5vMnFkL0d2Ym0KNDAxMnJIVUhJWTRONW9HaVdETnM0VnFYMmtIT2JPb0ZHbkhXMW0xMGlYSzBsQmdISjNkUHgrZGxkS2tGZ2w1awpkTXdZZVRIZWlObUZvNHdpVE52OXNOdzcxdlJGekY2SGxGSDdFVVZmZ3luR0NEM05qZkc5OWsxeWhvb29vU25aCjlMNjVpZms0cDFlYmJPUDFzbmdMUW9YRkdGQ2NNa3E2MjRvQ20wQkpkTGtUTnVtNkg3cGN5N1ZWM0tlVUVWcm4KRWxGS0FLWTNuczAxajd2bHhvK25wZVZoR0Z1UnowclMyRGhCMXIzRys5Q3dMUWdpQytzcENjNXVGOCt6RkVmVQpSQVZxcjg5TnJZeGdYQVkxTkhDSkhnWGFhM1N4VlcwMTRhdGs3cndlSlo2UDYvOFNheFpMZGhYbHZwRFF3TFBNCkpRQ0RyanZ1SmpMV0ZmVHowOWdwTDdZZ3U5ZDBNem5GNEx0cEJBeWtEU3RNWVI5SVIybHBiMFduZU56NExzc3cKSFpRcjdtV2pjcjM2alFZWGgzWFVheHNYV1hWdnVKdDIzbWdPWUcwYTBTcE1YQ0JnWW9tdVBhN1pPZTNNRUhJTQpFQ01OUW9SeEh2Z3RrbEZOUElkZlQ4YXVXakxCbElHRmtENTBvNmQxdVhtWExwS2ZlUHdHNit1RnNxUjZNbUNnCmNGZnRPUEI1RFFkRTIrRndXQlZzWmlRYVI2TENJbjM2eGZYemZHU0FQRlZnaFA1T2U4VERvcXZQRi96bVN4ZTEKUngzSFd6c1RHbkF6MEJtMjgyM1I1eFd1cnMrd0NZZm8rRVU0NGppTFFGMVJwUmU1d29rOTVPRDcySlJIelhDbQpTUlNPMURYelgweW11ZGdRCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://team4akscluster-dns-5f202574.hcp.eastus.azmk8s.io:443
  name: Team4AKSCluster
contexts:
- context:
    cluster: Team4AKSCluster
    user: clusterUser_rg-team4-container_Team4AKSCluster
  name: Team4AKSCluster
current-context: Team4AKSCluster
kind: Config
preferences: {}
users:
- name: clusterUser_rg-team4-container_Team4AKSCluster
  user:
    auth-provider:
      config:
        apiserver-id: 6dae42f8-4368-4678-94ff-3960e28e3630
        client-id: 80faf920-1908-4b52-b5ef-a8e7bedfc67a
        config-mode: "1"
        environment: AzurePublicCloud
        tenant-id: 4983693c-0a59-40de-92c7-eeb5ea6513d9
      name: azure
